/*
 * This source file was generated by the Gradle 'init' task
 */
package org.Project;

import org.Project.Entity.Ticket;
import org.Project.Entity.Train;
import org.Project.Entity.User;
import org.Project.Service.TicketServices;
import org.Project.Service.UserService;

import java.util.List;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        UserService userService = new UserService();
        TicketServices ticketServices = new TicketServices();




        System.out.println("Welcome to  Travel  Companion");

        while (true){

            System.out.println("%%%%%%%%%%%%%%%%% Menu %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%");
            System.out.println("1. SIGN IN (NEW USER)");
            System.out.println("2. LOG IN");
            System.out.println("7. EXIT\n\n");

            System.out.println("Enter your choice ");
            int ch = sc.nextInt();
            sc.nextLine();

            switch (ch){
                case 1 :
                    System.out.println("Sign In Window");
                    System.out.println("Enter your name : ");
                    String name = sc.nextLine();
                    System.out.println("\n");
                    System.out.println("Enter your password");
                    String pass = sc.next();
                    userService.userSignIn(name,pass);
                    break;

                case 2 :
                    System.out.println("Log In window");
                    System.out.println("Enter your username");
                    String userName = sc.nextLine();
                    System.out.println("Enter your password");
                    String password = sc.next();

                    User user = userService.userLogin(userName,password);

                    if(user == null){
                        break;
                    }else {
                        while (true){
                            System.out.println("______________Services_______________");
                            System.out.println("1. SEARCH TRAIN");
                            System.out.println("2. BOOK TICKET");
                            System.out.println("3. FETCH YOUR TICKETS");
                            System.out.println("4. CANCEL TICKET");
                            System.out.println("5. Log Out\n\n");

                            System.out.println("Enter your choice : ");
                            int choice = sc.nextInt();

                            switch(choice){
                                case 1 :
                                    System.out.println("+++++++++++++Search train++++++++++++++");
                                    System.out.println("Enter Source for Travel");
                                    String source = sc.next();
                                    System.out.println("Enter your destination for travel");
                                    String destination = sc.next();

                                    System.out.println("========Available trains======== ");
                                    List matchedTrains = ticketServices.searchTrain(source,destination);

                                    for (Object train : matchedTrains){
                                        System.out.println(train);
                                        System.out.println();
                                    }
                                    break;

                                case 2 :
                                    System.out.println("^^^^^^^^^^^^^^Ticket Booking^^^^^^^^^^^^^^");
                                    System.out.println("Enter trainID");
                                    String trainId = sc.next();
                                    System.out.println("Enter Source for Travel");
                                    String Source = sc.next();
                                    System.out.println("Enter your destination for travel");
                                    String Destination = sc.next();
                                    System.out.println("Enter date of travel (dd-mm-yyyy)");
                                    String dateOfTravel = sc.next();

                                    ticketServices.bookTicket(user,Source,Destination,dateOfTravel,trainId);
                                    break;

                                case 3 :
                                    System.out.println("@@@@@@@@@@@@@@@@Your Tickets@@@@@@@@@@@@@@@");
                                    System.out.println("Enter your username");
                                    String user_name = sc.next();
                                    ticketServices.fetchTickets(user_name);
                                    break;

                                case 4 :
                                    System.out.println("!!!!!!!!!!!! cancel your ticket !!!!!!!!!!!!!!");
                                    System.out.println("Enter your ticketID");
                                    String ticketId = sc.next();
                                    ticketServices.cancelTicket(user,ticketId);
                                    break;
                                case 5 :
                                    System.out.println("User Logged Out Successfully");
                                    continue;

                                default :
                                    System.out.println("Enter valid option");
                            }


                        }
                    }
                default :
                    System.out.println("Enter valid option");

            }
        }


    }


}